config/routes.rb
Rails.application.routes.draw do
  
  root to: "public/homes#top"
  
  # 顧客
  namespace :public do
    
    get "/about" => "homes#about", as: "about"
    
    resources :items, only: [:index, :show]
    
    get '/customers/unsubscribe' => "customers#unsubscribe", as: "unsubscribe"
    patch '/customers/withdraw' => "customers#withdraw", as: "withdraw"
    resources :customers, only: [:show, :edit, :update]
    
    delete 'cart_items/destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    
    
    get '/orders/complete'
    post '/orders/confirm'
    resources :orders, only: [:new, :create, :index, :show]
    
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
  
  # 管理者
  namespace :admin do
    get '/' => "homes#top"
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
  end

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  def subtotal
      item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  
  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  def with_tax_price
    (price * 1.1).floor
  end
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  
  
  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  
  def subtotal
      item.with_tax_price * amount
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page]).order(created_at: :desc)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end 
  
  private
  
  def customer_params
    params.recuire(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number, :is_active, :email)
  end 
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all.order(created_at: :desc)
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).order(created_at: :desc)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def index
    @items = Item.page(params[:page]).order(created_at: :desc)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genre = Genre.all
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end 
    
  
  private
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image, :genre_id)
  end 
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @order.shipping_cost = "800"
    @total_price = @order_details.sum{|order_detail|order_detail.subtotal}
    @total_payment = @order.shipping_cost + @total_price
  end
  
  private
  
  def order_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :shipping_cost, :total_payment, :payment_method)
  end 
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for(resource)
    public_customer_path
  end

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when Customer
      root_path
    end
  end

  def after_sign_out_path_for(resource)
    if resource == :admin
      new_admin_session_path
    else
      root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <h4 class="col-4 mt-3 text-center bg-light text-dark"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h4>
  <div class="row mt-5">
    <div class="col-lg-6 mx-auto">
      <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch, local: true do |f| %>
      <div class="row mb-3">
        <label class="col-lg-3 col-form-label">会員ID</label>
        <div class="col-lg-8">
          <%= @customer.id %>
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-lg-3 col-form-label">氏名</label>
        <div class="col-lg-3">
          <%= f.text_field :last_name, class: "form-control customer_last_name" %>
        </div>
        <div class="col-lg-3">
          <%= f.text_field :first_name, class: "form-control customer_first_name" %>
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-lg-3 col-form-label">フリガナ</label>
        <div class="col-lg-3">
          <%= f.text_field :last_name_kana, class: "form-control customer_last_name_kana" %>
        </div>
        <div class="col-lg-3">
          <%= f.text_field :first_name_kana, class: "form-control customer_first_name_kana" %>
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-lg-3 col-form-label">郵便番号</label>
        <div class="col-lg-3">
          <%= f.text_field :postal_code, class: "form-control customer_postal_code" %>
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-lg-3 col-form-label">住所</label>
        <div class="col-lg-8">
          <%= f.text_field :address, class: "form-control customer_address" %>
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-lg-3 col-form-label">電話番号</label>
        <div class="col-lg-3">
          <%= f.text_field :telephone_number, class: "form-control customer_telephone_number" %>
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-lg-3 col-form-label">メールアドレス</label>
        <div class="col-lg-8">
          <%= f.email_field :email, class: "form-control customer_email" %>
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-lg-3 col-form-label">会員ステータス</label>
        <div class="col-lg-8">
          <%= f.radio_button :is_active, :true %>
          <%= f.label :is_active, "有効", {value: :true, style: "display: inline-block;"} %>
          <%= f.radio_button :is_active, :false %>
          <%= f.label :is_active, "退会", {value: :false, style: "display: inline-block;"} %>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-3 mx-auto">
          <%= f.submit "　変更を保存　", class: "btn btn-lg btn-success" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <h3 class="col-2 mt-3 text-center bg-light text-dark">会員一覧</h3>
  </div>  
  <div class="row mt-5">
    <div class="col-lg-12">
      <table class="table">
        <thead class="table-active">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td><%= link_to "#{customer.last_name}#{customer.first_name}", admin_customer_path(customer.id), class: "text-dark" %></td>
            <td><%= customer.email%></td>
            <td>
              <% if customer.is_active %>
                <p class="text-success">有効</p>
              <% else %>
                <p clas="text-secondary">退会</p>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= paginate @customers%>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <h4 class="col-4 mt-3 text-center bg-light text-dark"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h4>
  <div class="row mb-3">
    <label class="col-lg-3 col-form-label">会員ID</label>
    <div class="col-lg-6 d-flex align-items-center">
      <%= @customer.id %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-lg-3 col-form-label">氏名</label>
    <div class="col-lg-6 d-flex align-items-center">
      <%= @customer.last_name %>
      <%= @customer.first_name %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-lg-3 col-form-label">フリガナ</label>
    <div class="col-lg-6 d-flex align-items-center">
      <%= @customer.last_name_kana %>
      <%= @customer.first_name_kana %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-lg-3 col-form-label">郵便番号</label>
    <div class="col-lg-6 d-flex align-items-center">
      <%= @customer.postal_code %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-lg-3 col-form-label">住所</label>
    <div class="col-lg-6 d-flex align-items-center">
      <%= @customer.address %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-lg-3 col-form-label">電話番号</label>
    <div class="col-lg-6 d-flex align-items-center">
      <%= @customer.telephone_number %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-lg-3 col-form-label">メールアドレス</label>
    <div class="col-lg-6 d-flex align-items-center">
      <%= @customer.email %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-lg-3 col-form-label">会員ステータス</label>
    <div class="col-lg-6 d-flex align-items-center">
      <% if @customer.is_active %>
        <strong><p class="text-success">有効</p></strong>
      <% else %>
        <strong><p class="text-secondary">退会</p></strong>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-3 mx-auto">
      <%= link_to " 編集する ", edit_admin_customer_path(@customer.id), class: "btn btn-lg btn-success" %>
    </div>
  </div>
</div>

app/views/admin/genres/edit.html.erb
<div class="container">
  <h4 class="col-3 mt-3 text-center bg-light text-dark">ジャンル編集</h4>
  <div class="row">
    <div class="col-lg-7 mt-5">
      <%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :patch, local: true do |f| %>
      <div class="row">
        <p class="col-lg-2 mx-auto">ジャンル名</p>
        <div class="col-lg-5">
          <%= f.text_field :name, class: "form-control name", placeholder: "ジャンル名" %>
        </div>
        <div class="col-lg-5 mx-auto">
          <%= f.submit "  変更を保存  ", class: "btn btn-success" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <h3 class="col-4 mt-3 text-center bg-light text-dark">ジャンル一覧・追加</h3>
  <div class="row">
    <div class="col-lg-7 mt-5">
      <%= form_with model: @genre, url: admin_genres_path, local: true do |f| %>
      <div class="row">
        <p class="col-lg-2 mx-auto">ジャンル名</p>
        <div class="col-lg-5">
          <%= f.text_field :name, class: "form-control name", placeholder: "ジャンル名" %>
        </div>
        <div class="col-lg-5 mx-auto">
          <%= f.submit "    新規登録    ", class: "btn btn-success" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-5 mt-5">
      <table class="table">
        <thead class="thead-light py-2">
          <tr>
            <th>ジャンル</th>
            <th colspan="4"></th>
          </tr>
        </thead>
        <tbody class="py-2">
          <% @genres.each do |genre| %>
          <tr>
            <td class="text-left"><%= genre.name %></td>
            <td class="text-right"><%= link_to "  編集する  ", edit_admin_genre_path(genre.id), class: "btn btn-sm btn-success" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <h3 class="col-3 mt-3 text-center bg-light text-dark">商品編集</h3>
  <div class="row mt-5">
    <div class="col-lg-6 mx-auto">
      <%= form_with model: @item, url: admin_item_path(@item.id), method: :patch, local: true do |f| %>
      <div class="row mb-3">
        <label class="col-lg-3 col-form-label">商品画像</label>
        <div class="col-lg-8">
          <%= f.file_field :image, class: "form-control-file image" %>
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-lg-3 col-form-label">商品名</label>
        <div class="col-lg-8">
          <%= f.text_field :name, class: "form-control name" %>
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-lg-3 col-form-label">商品説明</label>
        <div class="col-lg-8">
          <%= f.text_area :introduction, class: "form-control introduction", rows: "10" %>
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-lg-3 col-form-label">ジャンル</label>
        <div class="col-lg-8">
          <%= f.collection_select(:genre_id, Genre.all, :id, :name, include_blank: '--選択してください--', class: "custom-select") %>
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-lg-3 col-form-label">税抜価格</label>
        <div class="col-lg-8">
          <%= f.text_field :price, class: "form-control price" %>
        </div>
        <span class="col-lg-1 px-0 pt-2 text-left">円</span>
      </div>
      <div class="row">
        <div class="col-lg-3 mx-auto">
          <%= f.submit "　変更を保存　", class: "btn btn-lg btn-success text-center" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-lg-10">
      <h3 class="col-3 mt-3 text-center bg-light text-dark">商品一覧</h3>
    </div>
    <div class="col-l2">
      <%= link_to new_admin_item_path, class: " fa-2x" do %>
        <i class="fa-solid fa-circle-plus"></i>
      <% end %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-lg-12">
      <table class="table">
        <thead class="table-active">
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td><%= link_to item.name, admin_item_path(item.id), class: "text-dark" %></td>
            <td><%= item.price.to_s(:delimited) %></td>
            <td><%= item.genre.name %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= paginate @items %>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <h3 class="col-3 mt-3 text-center bg-light text-dark">商品新規登録</h3>
  <div class="row mt-5">
    <div class="col-lg-6 mx-auto">
      <%= form_with model: @item, url: admin_items_path, local: true do |f| %>
      <div class="row mb-3">
        <label class="col-lg-3 col-form-label">商品画像</label>
        <div class="col-lg-8">
          <%= f.file_field :image, class: "form-control-file image" %>
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-lg-3 col-form-label">商品名</label>
        <div class="col-lg-8">
          <%= f.text_field :name, placeholder: "商品名", class: "form-control name" %>
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-lg-3 col-form-label">商品説明</label>
        <div class="col-lg-8">
          <%= f.text_area :introduction, placeholder: "ここに説明文を記述します", class: "form-control introduction", rows: "10" %>
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-lg-3 col-form-label">ジャンル</label>
        <div class="col-lg-8">
          <%= f.collection_select(:genre_id, Genre.all, :id, :name, include_blank: '--選択してください--', class: "custom-select") %>
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-lg-3 col-form-label">税抜価格</label>
        <div class="col-lg-8">
          <%= f.text_field :price, placeholder: "1000", class: "form-control price" %>
        </div>
        <span class="col-lg-1 px-0 pt-2 text-left">円</span>
      </div>
      <div class="row">
        <div class="col-lg-3 mx-auto">
          <%= f.submit "　新規登録　", class: "btn btn-lg btn-success text-center" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <h3 class="col-3 mt-3 text-center bg-light text-dark">商品詳細</h3>
  <div class="row">
    <div class="col-lg-4">
      <%= image_tag @item.get_image(200, 200) %>
    </div>
    <div class="col-lg-8">
      <div class="row mb-3">
        <label class="col-lg-3 col-form-label">商品名</label>
        <div class="col-lg-6 d-flex align-items-center">
          <%= @item.name %>
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-lg-3 col-form-label">商品説明</label>
        <div class="col-lg-6 d-flex align-items-center">
          <%= @item.introduction %>
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-lg-3 col-form-label">ジャンル</label>
        <div class="col-lg-6 d-flex align-items-center">
          <%= @item.genre.name %>
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-lg-3 col-form-label">税込価格<br>(税抜価格)</label>
        <div class="col-lg-6 d-flex align-items-center">
          <strong>
            <%= @item.with_tax_price.to_s(:delimited) %>(<%= @item.price.to_s(:delimited) %>)円
          </strong>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-3 mx-auto">
      <%= link_to "   編集する   ", edit_admin_item_path(@item.id), class: "btn btn-md btn-success" %>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <h3 class="col-3 mt-3 text-center bg-light text-dark">注文履歴詳細</h3>
  <div class="row mb-3">
    <label class="col-lg-3 col-form-label">購入者</label>
    <div class="col-lg-6 d-flex align-items-center">
      <%= link_to admin_customer_path(@order.customer_id), class: "text-dark" do %>
        <%= @order.customer.last_name %> <%= @order.customer.first_name %>
      <% end %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-lg-3 col-form-label">注文日</label>
    <div class="col-lg-6 d-flex align-items-center">
      <%= @order.created_at.strftime("%Y/%m/%d") %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-lg-3 col-form-label">配送先</label>
    <div class="col-lg-6 d-flex align-items-center">
      〒<%= @order.postal_code %>
      <%= @order.address %></br>
      <%= @order.name %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-lg-3 col-form-label">支払方法</label>
    <div class="col-lg-6 d-flex align-items-center">
      <%= @order.payment_method_i18n %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-9">
      <table class="table">
        <thead class="table-active">
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= order_detail.price.to_s(:delimited) %>円</td>
            <td><%= order_detail.amount %></td>
            <td><%= order_detail.subtotal.to_s(:delimited) %>円</td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-lg-3 payment-info mb-3">
      <table>
        <tbody>
          <tr>
            <th>商品合計</th>
            <td><%= @total_price.round.to_s(:delimited) %>円</td>
          </tr>
          <tr>
            <th>送料</th>
            <td><%= @order.shipping_cost.to_s(:delimited) %>円</td>
          </tr>
          <tr>
            <th>請求金額合計</th>
            <td><%= @total_payment.round.to_s(:delimited) %>円</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>