config/routes.rb
Rails.application.routes.draw do
  
  root to: "public/homes#top"
  
  # 顧客
  namespace :public do
    
    get "/about" => "homes#about", as: "about"
    
    resources :items, only: [:index, :show]
    
    get '/customers/unsubscribe' => "customers#unsubscribe", as: "unsubscribe"
    patch '/customers/withdraw' => "customers#withdraw", as: "withdraw"
    resources :customers, only: [:show, :edit, :update]
    
    delete 'cart_items/destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    
    
    get '/orders/complete'
    post '/orders/confirm'
    resources :orders, only: [:new, :create, :index, :show]
    
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
  
  # 管理者
  namespace :admin do
    get '/' => "homes#top"
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
  end

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  def subtotal
      item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  
  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  def with_tax_price
    (price * 1.1).floor
  end
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  
  
  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  
  def subtotal
      item.with_tax_price * amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all.order(created_at: :desc)
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).order(created_at: :desc)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def index
    @items = Item.page(params[:page]).order(created_at: :desc)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genre = Genre.all
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end 
    
  
  private
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image, :genre_id)
  end 
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @order.shipping_cost = "800"
    @total_price = @order_details.sum{|order_detail|order_detail.subtotal}
    @total_payment = @order.shipping_cost + @total_price
  end
  
  private
  
  def order_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :shipping_cost, :total_payment, :payment_method)
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for(resource)
    public_customer_path
  end

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when Customer
      root_path
    end
  end

  def after_sign_out_path_for(resource)
    if resource == :admin
      new_admin_session_path
    else
      root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm mb-5">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand" href="/"><%= image_tag 'logo.png', size: '180x100' %></a>
          <% if admin_signed_in? %>
            <ul class="nav justify-content-end">
              <li class="nav-item btn btn-outline-light"><%= link_to "商品一覧", admin_items_path, class: 'nav-link text-dark' %></li>
              <li class="nav-item btn btn-outline-light"><%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-dark' %></li>
              <li class="nav-item btn btn-outline-light"><%= link_to "注文履歴一覧", admin_path, class: 'nav-link text-dark' %></li>
              <li class="nav-item btn btn-outline-light"><%= link_to "ジャンル一覧", admin_genres_path,data: {"turbolinks"=>false}, class: 'nav-link text-dark' %></li>
              <li class="nav-item btn btn-outline-light"><%= link_to "ログアウト",  destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %></li>
            </ul>
          <% elsif customer_signed_in? %>
            <div class="mx-auto" style="width: 200px;">
              ようこそ、<%= current_customer.last_name %>さん！
            </div>
            <ul class="nav justify-content-end">
              <li class="nav-item btn btn-outline-light"><%= link_to "マイページ", public_customer_path(current_customer.id), class: 'nav-link text-dark' %></li>
              <li class="nav-item btn btn-outline-light"><%= link_to "商品一覧", public_items_path, class: 'nav-link text-dark' %></li>
              <li class="nav-item btn btn-outline-light"><%= link_to "カート", public_cart_items_path(current_customer.id),data: {"turbolinks"=>false}, class: 'nav-link text-dark' %></li>
              <li class="nav-item btn btn-outline-light"><%= link_to "ログアウト",  destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %></li>
            </ul>
          <% else %>
            <ul class="nav justify-content-end">
              <li class="nav-item btn btn-outline-light"><%= link_to "About", public_about_path, class: 'nav-link text-dark' %></li>
              <li class="nav-item btn btn-outline-light"><%= link_to "商品一覧", public_items_path,data: {"turbolinks"=>false}, class: 'nav-link text-dark' %></li>
              <li class="nav-item btn btn-outline-light"><%= link_to "新規登録", new_customer_registration_path,data: {"turbolinks"=>false}, class: 'nav-link text-dark' %></li>
              <li class="nav-item btn btn-outline-light"><%= link_to "ログイン", new_customer_session_path,data: {"turbolinks"=>false}, class: 'nav-link text-dark' %></li>
            </ul>
          <% end %>
        </div>
      </nav>
    </header>
    <main>
    <%= yield %>
    </main>
    <footer>
      <div>
          
          
      </div>
    </footer>
  </body>
</html>